### ISSUE TITLE
Error while building against 2.6.28-15-server on Ubuntu Desktop 9.04

### ISSUE THREAD

**Issue by tomasz-kuzemko** [tetromino/lenovo-sl-laptop#2]
I received the following error while trying to build the latest snapshot of lenovo-sl-laptop against 2.6.28-15-server kernel (from repository, with appropriate headers present) on Ubuntu 9.04 Desktop. When using 2.6.28-14-server it builds fine, so does 2.6.28-15-generic. I'm not quite sure if it's related to the kernel package or to your module. My laptop is Lenovo SL500.
# uname -a

Linux lenovo 2.6.28-15-server #48-Ubuntu SMP Wed Jul 29 09:57:16 UTC 2009 i686 GNU/Linux
# gcc -v

Using built-in specs.
Target: i486-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.3.3-5ubuntu4' --with-bugurl=file:///usr/share/doc/gcc-4.3/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --enable-shared --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --enable-nls --with-gxx-include-dir=/usr/include/c++/4.3 --program-suffix=-4.3 --enable-clocale=gnu --enable-libstdcxx-debug --enable-objc-gc --enable-mpfr --enable-targets=all --with-tune=generic --enable-checking=release --build=i486-linux-gnu --host=i486-linux-gnu --target=i486-linux-gnu
Thread model: posix
gcc version 4.3.3 (Ubuntu 4.3.3-5ubuntu4) 

==== BEGIN REPORT ====
# LC_ALL=POSIX make

make -C /lib/modules/2.6.28-15-server/build M=/usr/local/src/lenovo-sl-laptop modules
make[1]: Entering directory `/usr/src/linux-headers-2.6.28-15-server'
  CC [M]  /usr/local/src/lenovo-sl-laptop/lenovo-sl-laptop.o
In file included from include/linux/gfp.h:4,
                 from include/linux/kmod.h:22,
                 from include/linux/module.h:13,
                 from /usr/local/src/lenovo-sl-laptop/lenovo-sl-laptop.c:29:
include/linux/mmzone.h:18:26: error: linux/bounds.h: No such file or directory
include/linux/mmzone.h:256:5: warning: "MAX_NR_ZONES" is not defined
In file included from include/linux/gfp.h:4,
                 from include/linux/kmod.h:22,
                 from include/linux/module.h:13,
                 from /usr/local/src/lenovo-sl-laptop/lenovo-sl-laptop.c:29:
include/linux/mmzone.h:277: error: 'MAX_NR_ZONES' undeclared here (not in a function)
make[2]: *** [/usr/local/src/lenovo-sl-laptop/lenovo-sl-laptop.o] Error 1
make[1]: *** [_module_/usr/local/src/lenovo-sl-laptop] Error 2
make[1]: Leaving directory`/usr/src/linux-headers-2.6.28-15-server'
make: **\* [all] Error 2
==== END REPORT ====

**Comment by tomasz-kuzemko** [comment]
Sorry, was building with corrupt headers package, everything build fine.

**Comment by tetromino** [comment]
Since everything is fine, I'm closing the bug report.
